name: hansarhotels
favicon: null
layout_spectrum: 0.27158224768936634
typography_spectrum: 0.7225539269857109
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6410979512147605
  lightness: 0.9210136514157057
  saturation: 0.9010144146159291
  rhythmicContrast: 0.3009800969157368
purpose: []
